Repository LM-channel-team-project/WantoDo, pull requests merged in 2021-05, with the labels that each got.

#84 [Add] tag.model 관련 스키마 생성
  back/src/common/types.ts
  back/src/controllers/v1/tag.controller.ts
  back/src/models/tag.model.ts
  back/src/routes/index.ts
  back/src/routes/v1/tag.route.ts
  back/src/services/v1/tag.service.ts
Labels: 📟 백엔드

#111 [Add] 태그 css 스타일링
  front/src/App.jsx
  front/src/styles/Input.module.css
  front/src/styles/Tag.module.css
  front/src/styles/common/color.css
Labels: 📚Todo, 🖥 프론트엔드

#119 [Add] 투두리스트 css 스타일링
  front/src/components/TaskItem.jsx
  front/src/styles/Button.module.css
  front/src/styles/CheckButton.module.css
  front/src/styles/PriorityIcon.module.css
  front/src/styles/Tag.module.css
  front/src/styles/TaskItem.module.css
  front/src/styles/common/color.css
Labels: 🖥 프론트엔드

#124 [Add] tag 생성 API 외 4
  back/apidoc.json
  back/src/controllers/v1/tag.controller.ts
  back/src/models/tag.model.ts
  back/src/models/task.model.ts
  back/src/routes/v1/account.route.ts
  back/src/routes/v1/tag.route.ts
  back/src/routes/v1/task.route.ts
  back/src/services/v1/tag.service.ts
Labels: 📟 백엔드

#128 [Add] 투두리스트 체크에 따른 상태변화 css
  front/src/App.jsx
  front/src/styles/TaskItem.module.css
Labels: 🖥 프론트엔드

#129 feat/castleMo #116 #115 #117
  back/apidoc.json
  back/src/controllers/v1/tag.controller.ts
  back/src/routes/v1/tag.route.ts
  back/src/routes/v1/task.route.ts
  back/src/services/v1/tag.service.ts
Labels: 📟 백엔드

#134 Feat/castleMo #113 #135 #132
  back/apidoc.json
  back/src/controllers/v1/account.controller.ts
  back/src/controllers/v1/profile.controller.ts
  back/src/models/user.model.ts
  back/src/routes/v1/account.route.ts
  back/src/routes/v1/profile.route.ts
  back/src/services/v1/account.service.ts
  back/src/services/v1/profile.service.ts
  back/src/services/v1/tag.service.ts
  back/src/services/v1/task.service.ts
Labels: 📟 백엔드

#143 [Add] task modal css style
  front/src/components/TaskForm.jsx
  front/src/styles/Button.module.css
  front/src/styles/Input.module.css
  front/src/styles/InputBox.module.css
  front/src/styles/Modal.module.css
  front/src/styles/PeriodsInputBox.module.css
  front/src/styles/PriorityIcon.module.css
  front/src/styles/PrioritySelector.module.css
  front/src/styles/TaskForm.module.css
  front/src/styles/common/color.css
Labels: 🖥 프론트엔드

#141 feat/castleMo #131
  back/src/controllers/v1/profile.controller.ts
  back/src/routes/v1/profile.route.ts
  back/src/services/v1/profile.service.ts
Labels: 📟 백엔드

#147 Feat/castleMo #146 #99
  back/src/controllers/v1/task.controller.ts
  back/src/models/task.model.ts
  back/src/routes/v1/tag.route.ts
  back/src/routes/v1/task.route.ts
  back/src/services/v1/task.service.ts
Labels: 📟 백엔드

#149 [Add] 캘린더 스타일링
  front/src/components/Calendar.jsx
  front/src/styles/Button.module.css
  front/src/styles/Calendar.module.css
Labels: 🖥 프론트엔드

#165 [Add] css 수정 및 로그인 페이지 스타일링
  front/src/components/BrightStar.jsx
  front/src/components/GoogleLoginButton.jsx
  front/src/styles/Button.module.css
  front/src/styles/Calendar.module.css
  front/src/styles/CheckButton.module.css
  front/src/styles/IconButton.module.css
  front/src/styles/MenuSelector.module.css
  front/src/styles/PriorityIcon.module.css
  front/src/styles/TaskItem.module.css
Labels: 📚Todo, 🖥 프론트엔드

#183 Feat/castle mo
  back/src/app.ts
  back/src/controllers/v1/task.controller.ts
  back/src/routes/v1/tag.route.ts
  back/src/routes/v1/task.route.ts
  back/src/services/v1/tag.service.ts
  back/src/services/v1/task.service.ts
Labels: 📚Todo, 📟 백엔드

#191 [Feat] 로그인(이름, 좌우명 창) css 수정
  front/src/styles/Button.module.css
  front/src/styles/Input.module.css
  front/src/styles/InputBox.module.css
  front/src/styles/ProfileImage.module.css
  front/src/styles/page/Login.module.css
Labels: 🖥 프론트엔드, 🙀 도와줘~

#204 [Add] 로그인 튜토리얼 창 세부 수정
  front/src/components/PeriodInputBox.jsx
  front/src/styles/Button.module.css
  front/src/styles/DateInputBox.module.css
  front/src/styles/Input.module.css
  front/src/styles/InputBox.module.css
  front/src/styles/PeriodsInputBox.module.css
  front/src/styles/PrioritySelector.module.css
  front/src/styles/QuickAddForm.module.css
  front/src/styles/TaskForm.module.css
  front/src/styles/page/Login.module.css
Labels: 🖥 프론트엔드

#192 Feat/castleMo #186 #226 #225
  back/src/app.ts
  back/src/controllers/v1/task.controller.ts
  back/src/models/task.model.ts
  back/src/routes/v1/task.route.ts
  back/src/services/v1/task.service.ts
Labels: 📚Todo, 📟 백엔드

#228 [feat] 테스크 모달 글자 스타일 수정 #213
  front/src/styles/InputBox.module.css
Labels: 🖥 프론트엔드

#239 [Feat] 태스크폼, 캘린더 월, 설정 창 스타일링 및 오류수정
  front/src/styles/Calendar.module.css
  front/src/styles/Input.module.css
  front/src/styles/TaskForm.module.css
  front/src/styles/ToggleSwitch.module.css
  front/src/styles/page/Main.module.css
Labels: 🖥 프론트엔드

#245 Feat/front 프로필 모달 창 수정 방법 변경
  front/src/components/ProfileModal.jsx
  front/src/styles/Button.module.css
  front/src/styles/ProfileModal.module.css
Labels: 🖥 프론트엔드

#252 [fix] 프로필 모달 오류 수정
  front/src/components/ProfileModal.jsx
  front/src/page/Main.jsx
  front/src/styles/Button.module.css
  front/src/styles/ProfileModal.module.css
Labels: 🖥 프론트엔드

#261 [Feat] css 수정
  front/src/container/TagModal.jsx
  front/src/container/TasksContainer.jsx
  front/src/container/WithdrawalModal.jsx
  front/src/styles/Button.module.css
  front/src/styles/CategoryDivider.module.css
  front/src/styles/CheckButton.module.css
  front/src/styles/DailyContainer.module.css
  front/src/styles/DailyNavbar.module.css
  front/src/styles/Input.module.css
  front/src/styles/Tag.module.css
  front/src/styles/TagModal.module.css
  front/src/styles/TaskItem.module.css
  front/src/styles/common/color.css
  front/src/styles/page/Main.module.css
Labels: 📚Todo, 🖥 프론트엔드, 🙀 도와줘~

#273 [Feat] 데일리 투데이 css 스타일링
  front/src/styles/Button.module.css
Labels: 🖥 프론트엔드
