Repository LM-channel-team-project/WantoDo, pull requests merged in 2021-04, with the labels that each got.

#3 Feat/castle mo
  .gitignore
Labels: 버그

#5 [Add] module추가 및 tsconfig 설정
  back/package.json
  back/tsconfig.json
Labels: 백엔드

#6 [Add] backend model 정의
  back/app.ts
  back/src/models/task.model.ts
  back/src/models/user.model.ts
Labels: 백엔드

#7 [Add] Directory 구조 생성
  back/app.ts
  back/package.json
  back/src/common/Utils.ts
  back/src/controllers/v1/account.controller.ts
  back/src/errors/index.ts
  back/src/lib/index.ts
  back/src/middlewares/index.ts
  back/src/routes/index.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 백엔드

#8 [Fix] 코드 추가 및 코드 정렬
  back/app.ts
  back/src/lib/wantodoMongoose.ts
  back/src/models/task.model.ts
  back/src/models/user.model.ts
Labels: 백엔드

#14 feat/castleMo
  back/app.ts
  back/package.json
  back/src/common/types.ts
  back/src/controllers/v1/account.controller.ts
  back/src/middlewares/Google.ts
  back/src/models/user.model.ts
  back/src/routes/index.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 백엔드

#13 [Chore] front 프리티어 세팅 #12 외 5개
  .gitignore
  front/.eslintrc.js
  front/.prettierrc.js
  front/package.json
  front/src/App.jsx
  front/src/components/InputBox.jsx
  front/src/index.js
  front/src/styles/InputBox.module.css
  front/src/styles/common/color.css
  front/src/styles/common/reset.css
  front/src/styles/common/size.css
  front/yarn.lock
Labels: 프론트엔드

#17 feat/castleMo
  back/src/common/types.ts
  back/src/controllers/v1/account.controller.ts
  back/src/models/task.model.ts
  back/src/models/user.model.ts
  back/src/routes/index.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 백엔드

#18 [Add] 재사용컴포넌트 인풋박스 css 스타일링
  front/src/styles/InputBox.module.css
  front/src/styles/common/color.css
  front/src/styles/common/size.css
Labels: 프론트엔드

#19 [Chore] react-icons 라이브러리 추가
  front/package.json
  front/yarn.lock
Labels: 프론트엔드

#20 [Add] 버튼 컴포넌트 추가 외 2
  front/src/App.jsx
  front/src/components/Button.jsx
  front/src/components/IconButton.jsx
  front/src/styles/Button.module.css
  front/src/styles/IconButton.module.css
Labels: 프론트엔드

#21 [Add] 회원탈퇴기능 추가 외 3
  back/src/controllers/v1/account.controller.ts
  back/src/middlewares/Google.ts
  back/src/models/task.model.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 백엔드

#23 [add] 프로필 조회 라우터/ 컨트롤러 작성
  back/src/controllers/v1/account.controller.ts
  back/src/controllers/v1/profile.controller.ts
  back/src/middlewares/Google.ts
  back/src/routes/v1/profile.route.ts
  back/src/services/v1/profile.service.ts
Labels: 백엔드

#22 [Add] MenuSelector 컴포넌트 추가 외 2
  front/public/assets/images/default_profile.png
  front/src/App.jsx
  front/src/components/MenuSelector.jsx
  front/src/components/ProfileButon.jsx
  front/src/container/Navbar.jsx
  front/src/styles/MenuSelector.module.css
  front/src/styles/Navbar.module.css
  front/src/styles/ProfileButton.module.css
Labels: 프론트엔드

#27 Create issues todo_template
  .github/ISSUE_TEMPLATE/todo_template
Labels: 👍 제안, 📄 문서

#28 [Fix] markdown 파일로 변경
  .github/ISSUE_TEMPLATE/todo_template.md
Labels: 📄 문서

#25 [add] 프로필 조회 서비스.ts 코드 추가
  back/src/routes/index.ts
  back/src/routes/v1/profile.route.ts
  back/src/services/v1/profile.service.ts
Labels: 📚Todo, 📟 백엔드

#31 Account docs 생성 외 1
  back/package.json
  back/src/controllers/v1/account.controller.ts
  back/src/routes/index.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 📄 문서, 📟 백엔드

#24 [Add] 버튼 컴포넌트 css 스타일링
  front/src/styles/Button.module.css
  front/src/styles/IconButton.module.css
  front/src/styles/InputBox.module.css
  front/src/styles/common/color.css
  front/src/styles/common/size.css
Labels: 🖥 프론트엔드

#34 [Add] Css common 파일 추가 및 수정
  front/src/styles/Button.module.css
  front/src/styles/InputBox.module.css
  front/src/styles/common/effect.css
  front/src/styles/common/size.css
Labels: 🖥 프론트엔드

#40 feat/castleMo
  back/.eslintrc.json
  back/apidoc.json
  back/app.ts
  back/package-lock.json
  back/package.json
  back/prettierrc.json
  back/src/common/types.ts
  back/src/controllers/v1/account.controller.ts
  back/src/controllers/v1/profile.controller.ts
  back/src/lib/wantodoMongoose.ts
  back/src/middlewares/Google.ts
  back/src/models/task.model.ts
  back/src/models/user.model.ts
  back/src/routes/index.ts
  back/src/routes/v1/account.route.ts
  back/src/routes/v1/profile.route.ts
  back/src/services/v1/account.service.ts
  back/src/services/v1/profile.service.ts
Labels: 📚Todo, 📟 백엔드

#52 [Add] 프로필 css 스타일링
  front/src/components/ProfileModal.jsx
  front/src/styles/Button.module.css
  front/src/styles/Modal.module.css
  front/src/styles/ProfileImage.module.css
  front/src/styles/ProfileModal.module.css
  front/src/styles/common/color.css
  front/src/styles/common/size.css
Labels: 🖥 프론트엔드

#58 [Fix] 개발 서버 실행 오류 수정
  front/src/App.jsx
  front/src/components/ProfileImage.jsx
  front/src/container/Modal.jsx
  front/src/container/Navbar.jsx
Labels: 🐛 버그, 🖥 프론트엔드

#64 [Add] 버튼 컴포넌트 css 클래스 수정
  front/src/styles/Button.module.css
  front/src/styles/common/color.css
  front/src/styles/common/reset.css
  front/src/styles/common/size.css
Labels: 🖥 프론트엔드

#79 [Add] navbar css 스타일링
  front/src/App.jsx
  front/src/styles/Button.module.css
  front/src/styles/MenuSelector.module.css
  front/src/styles/Navbar.module.css
  front/src/styles/common/color.css
Labels: 🖥 프론트엔드

#78 [Fix] user Schema 수정
  back/package-lock.json
  back/src/controllers/v1/account.controller.ts
  back/src/lib/wantodoSchedule.ts
  back/src/models/user.model.ts
  back/src/routes/v1/account.route.ts
  back/src/services/v1/account.service.ts
Labels: 📚Todo, 📟 백엔드

#100 [Add] 퀵버튼 css 스타일링
  front/src/styles/Button.module.css
Labels: 🖥 프론트엔드

#110 [Add]README.md 시안
  README.md
Labels: 👍 제안, 🖥 프론트엔드
